name: ActionIn

volumes:
  action_in_data:

services:
  postgres:
    container_name: ActionInBackend
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ActionIn
    ports:
      - "5432:5432"
    volumes:
      - action_in_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 15s
      retries: 3

# pgcli -h localhost -U postgres -d ActionIn
# OR
# pgcli postgresql://postgres:postgres@localhost/Expenses
